framework:
    messenger:
        transports:
            config_import_message:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                options:
                    exchange:
                        name: 'config_message_%env(APP_ENV)%'
                    queues:
                        'config_message_%env(APP_ENV)%': ~
        routing:
#            'App\Message\Config\ConfigImportMessage': config_message
            'App\Message\Config\ConfigImportMessage': sync
