framework:
    messenger:
        transports:
            export_file_message:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                options:
                    exchange:
                        name: 'export_file_message_%env(APP_ENV)%'
                    queues:
                        'export_file_message_%env(APP_ENV)%': ~
        routing:
            'App\Message\ExportFile\ExportFileMessage': export_file_message
